name: Build Release

on:
  push:
    tags:
      - "*"

jobs:
  build-ankiaddon:
    runs-on: ubuntu-latest

    steps:
      - name: Set env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Create dist folder
        shell: bash
        run: |
          mkdir dist
      - name: Set version
        shell: bash
        run: |
          echo "VERSION_STRING = '${{ env.RELEASE_VERSION }}'" > src/version.py
      - name: Zip
        shell: bash
        run: |
          cd src
          zip -r ../dist/Migaku.ankiaddon . -x user_files/\* meta.json
          cd ..
      - name: Upload artifacts
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
